// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBDEcommerceapp.Data;

#nullable disable

namespace SBDEcommerceapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325072144_AddProductsToDb")]
    partial class AddProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SBDEcommerceapp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Resolve"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Nova"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Forge"
                        });
                });

            modelBuilder.Entity("SBDEcommerceapp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "SBD",
                            Description = "High-performance training socks designed for comfort, durability, and support during intense workouts.",
                            ListPrice = 60.0,
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            SKU = "SBD-SOCK-001",
                            Title = "SBD Resolve Socks"
                        },
                        new
                        {
                            Id = 2,
                            Author = "SBD",
                            Description = "Heavy-duty lifting straps designed to improve grip and support during deadlifts and pulling exercises.",
                            ListPrice = 180.0,
                            Price = 160.0,
                            Price100 = 140.0,
                            Price50 = 150.0,
                            SKU = "SBD-STRAP-002",
                            Title = "SBD Nova Lifting Straps"
                        },
                        new
                        {
                            Id = 3,
                            Author = "SBD",
                            Description = "Comfortable and durable training t-shirt made with breathable fabric for everyday workouts.",
                            ListPrice = 120.0,
                            Price = 100.0,
                            Price100 = 80.0,
                            Price50 = 90.0,
                            SKU = "SBD-TSHIRT-003",
                            Title = "SBD Forge T-Shirt Standard"
                        },
                        new
                        {
                            Id = 4,
                            Author = "SBD",
                            Description = "Premium heavyweight hoodie designed for warmth, comfort, and durability during training or casual wear.",
                            ListPrice = 300.0,
                            Price = 270.0,
                            Price100 = 230.0,
                            Price50 = 250.0,
                            SKU = "SBD-HOODIE-004",
                            Title = "SBD Forge Hoodie"
                        },
                        new
                        {
                            Id = 5,
                            Author = "SBD",
                            Description = "Soft and durable sweatshirt ideal for training sessions and everyday use.",
                            ListPrice = 250.0,
                            Price = 220.0,
                            Price100 = 180.0,
                            Price50 = 200.0,
                            SKU = "SBD-SWEAT-005",
                            Title = "SBD Forge Sweatshirt"
                        },
                        new
                        {
                            Id = 6,
                            Author = "SBD",
                            Description = "Athletic joggers designed for flexibility, comfort, and performance in and out of the gym.",
                            ListPrice = 200.0,
                            Price = 180.0,
                            Price100 = 150.0,
                            Price50 = 160.0,
                            SKU = "SBD-JOGGER-006",
                            Title = "SBD Nova Joggers"
                        },
                        new
                        {
                            Id = 7,
                            Author = "SBD",
                            Description = "High-performance weightlifting t-shirt built for durability and comfort during heavy training.",
                            ListPrice = 130.0,
                            Price = 110.0,
                            Price100 = 90.0,
                            Price50 = 100.0,
                            SKU = "SBD-TSHIRT-007",
                            Title = "SBD Resolve Weightlifting T-Shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
